### ISSUE TITLE
在Arch Linux下无法安装

### ISSUE THREAD

**Issue by wxt1221** [luogu-dev/cyaron#106]
采用AUR进行安装，已经安装好xeger以及colorful，安装cyaron时报错：
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
/usr/lib/python3.11/site-packages/setuptools/command/test.py:194: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  ir_d = dist.fetch_build_eggs(dist.install_requires)
/usr/lib/python3.11/site-packages/setuptools/command/test.py:195: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  tr_d = dist.fetch_build_eggs(dist.tests_require or [])
/usr/lib/python3.11/site-packages/setuptools/command/test.py:196: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  er_d = dist.fetch_build_eggs(
running egg_info
writing cyaron.egg-info/PKG-INFO
writing dependency_links to cyaron.egg-info/dependency_links.txt
writing requirements to cyaron.egg-info/requires.txt
writing top-level names to cyaron.egg-info/top_level.txt
reading manifest file 'cyaron.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'cyaron.egg-info/SOURCES.txt'
running build_ext
cyaron (unittest.loader._FailedTest.cyaron) ... ERROR

======================================================================
ERROR: cyaron (unittest.loader._FailedTest.cyaron)
----------------------------------------------------------------------
ImportError: Failed to import test module: cyaron
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 440, in _find_test_path
    package = self._get_module_from_name(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/wxt/.cache/yay/python-cyaron/src/python-cyaron/cyaron/__init__.py", line 17, in <module>
    from .math import *
  File "/home/wxt/.cache/yay/python-cyaron/src/python-cyaron/cyaron/math.py", line 7, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.11/fractions.py)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>

系统：Arch Linux On x86-64
Python: 3.11.3

**Comment by wxt1221** [comment]
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.11/fractions.py)

**Comment by wxt1221** [comment]
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.11/fractions.py)

**Comment by wxt1221** [comment]
这是因为最新的发布版的问题，已经在主分支中修改。
