### ISSUE TITLE
Vector.random 随机取值的范围错误

### ISSUE THREAD

**Issue by weilycoder** [luogu-dev/cyaron#140]
跑一下 `Vector.random(1, [(10, 11)], VectorRandomMode.repeatable)` 就会报错，大家都只用默认的不带重复的是吧？

**我正在着手修复**

EDITED：一开始没加报错，下次一定注意

**Comment by weilycoder** [comment]
```
Traceback (most recent call last):
  File "d:/Admin/Desktop/IDE/github/cyaron/config.py", line 4, in <module>
    Vector.random(1, [(10, 11)], VectorRandomMode.repeatable)
  File "d:\Admin\Desktop\IDE\github\cyaron\cyaron\vector.py", line 57, in random
    result = [[random.randint(x, y) for x, y in zip(offset, length)] for _ in range(num)]
  File "d:\Admin\Desktop\IDE\github\cyaron\cyaron\vector.py", line 57, in <listcomp>
    result = [[random.randint(x, y) for x, y in zip(offset, length)] for _ in range(num)]
  File "d:\Admin\Desktop\IDE\github\cyaron\cyaron\vector.py", line 57, in <listcomp>
    result = [[random.randint(x, y) for x, y in zip(offset, length)] for _ in range(num)]
  File "D:\Program Files\Python38\lib\random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "D:\Program Files\Python38\lib\random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (10, 2, -8)
```

**Comment by weilycoder** [comment]
是有啥考量吗，可以 close 了吧
