### ISSUE TITLE
dec2base 函数出问题

### ISSUE THREAD

**Issue by StevenJinyanCheng** [luogu-dev/cyaron#150]
```
(base) PS C:\Users\Steve> python
Python 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from cyaron import *
>>> dec2base
<function dec2base at 0x0000020A73598900>
>>> dec2base(123,11)
'102'
>>> dec2base(123,111)
'1C'
>>> dec2base(1234,111)
'BD'
>>> dec2base(12345,111)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Steve\AppData\Roaming\Python\Python311\site-packages\cyaron\math.py", line 494, in dec2base
    return dec2base(n // base, base) + convert_string[n % base]
                                       ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: string index out of range
>>>
```
本应出ValueError
可改为：
```py

#source:
# http://interactivepython.org/runestone/static/pythonds/Recursion/pythondsConvertinganIntegertoaStringinAnyBase.html
def dec2base(n: int, base: int) -> str:
    """
    Convert a decimal number to a specified base.
    Args:
        n: The decimal number to convert.
        base: The base to convert the number to. Must be between 2 and 16.
    Returns:
        The number represented in the specified base.
    Raises:
        ValueError: If the base is not between 2 and 16.
    """
    # 增加下列几行
    if (base < 2) or (base > 16):
        raise ValueError("base is not between 2 and 16. ")
    # 结束
    convert_string = "0123456789ABCDEF"
    if n < base:
        return convert_string[n]
    return dec2base(n // base, base) + convert_string[n % base]

```

**Comment by weilycoder** [comment]
现在维护者是不是认为报错就行？其他文件中甚至有用 `Exception` 抛出异常的。

你可以去开个 pr，或者看他啥时候心情好了修掉。

**Comment by StevenJinyanCheng** [comment]
pr 是什么？

**Comment by StevenJinyanCheng** [comment]
再说了，可以2-36进制啊。
```py
#source:
# http://interactivepython.org/runestone/static/pythonds/Recursion/pythondsConvertinganIntegertoaStringinAnyBase.html
def dec2base(n: int, base: int) -> str:
    """
    Convert a decimal number to a specified base.
    Args:
        n: The decimal number to convert.
        base: The base to convert the number to. Must be between 2 and 36.
    Returns:
        The number represented in the specified base.
    Raises:
        ValueError: If the base is not between 2 and 36.
    """
    # 增加下列几行
    if (base < 2) or (base > 36):
        raise ValueError("base is not between 2 and 36. ")
    convert_string = "0123456789"
    for i in range(1, 26):
        convert_string = convert_string + chr(ord('A') + i - 1)
    # 结束
    if n < base:
        return convert_string[n]
    return dec2base(n // base, base) + convert_string[n % base]
    ```
（随手看了一眼原来代码，就发现有问题。）

**Comment by StevenJinyanCheng** [comment]
又出问题了。
```
(base) PS C:\Users\Steve> python
Python 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from cyaron import *
>>> n2words
<function n2words at 0x000001C2310E65C0>
>>> n2words(10**100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Steve\AppData\Roaming\Python\Python311\site-packages\cyaron\math.py", line 548, in n2words
    words.append(thousands[g] + '')
                 ~~~~~~~~~^^^
IndexError: list index out of range
>>> n2words(10**80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Steve\AppData\Roaming\Python\Python311\site-packages\cyaron\math.py", line 548, in n2words
    words.append(thousands[g] + '')
                 ~~~~~~~~~^^^
IndexError: list index out of range
>>> n2words(10**70)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Steve\AppData\Roaming\Python\Python311\site-packages\cyaron\math.py", line 548, in n2words
    words.append(thousands[g] + '')
                 ~~~~~~~~~^^^
IndexError: list index out of range
>>> n2words(10**60)
'One Vigintillion'
>>> n2words(10**63)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Steve\AppData\Roaming\Python\Python311\site-packages\cyaron\math.py", line 548, in n2words
    words.append(thousands[g] + '')
                 ~~~~~~~~~^^^
IndexError: list index out of range
>>> n2words(10**62)
'One Hundred Vigintillion'
>>> n2words(10**63-1)
'Nine Hundred Ninety Nine Vigintillion Nine Hundred Ninety Nine Novemdecillion Nine Hundred Ninety Nine Octodecillion Nine Hundred Ninety Nine Septendecillion Nine Hundred Ninety Nine Sexdecillion Nine Hundred Ninety Nine Quattuordecillion Nine Hundred Ninety Nine Tredecillion Nine Hundred Ninety Nine Duodecillion Nine Hundred Ninety Nine Undecillion Nine Hundred Ninety Nine Decillion Nine Hundred Ninety Nine Nonillion Nine Hundred Ninety Nine Octillion Nine Hundred Ninety Nine Septillion Nine Hundred Ninety Nine Sextillion Nine Hundred Ninety Nine Quintillion Nine Hundred Ninety Nine Quadrillion Nine Hundred Ninety Nine Trillion Nine Hundred Ninety Nine Billion Nine Hundred Ninety Nine Million Nine Hundred Ninety Nine Thousand Nine Hundred Ninety Nine'
>>>
```
怎么大于等于10的63次方就IndexError了？？？
大小写也不对啊，还没写 and

**Comment by Mr-Python-in-China** [comment]
> 怎么大于等于10的63次方就IndexError了？？？ 大小写也不对啊，还没写 and

你有啥要精确地读出 $10^{63}$ 以上的数的需求不

**Comment by weilycoder** [comment]
> 怎么大于等于10的63次方就IndexError了？？？

咋，就英语那玩意你要实现任意大小数字读出？

这不是很 useless 吗，而且应该完全不可做吧？

**Comment by StevenJinyanCheng** [comment]
之前没用过GitHub的Issues
