### ISSUE TITLE
怎么回事？说好的Polygon.simple_polygon输入一个n就可以生成随意多边形呢？

### ISSUE THREAD

**Issue by qwedc001** [luogu-dev/cyaron#33]
`p = Polygon.simple_polygon(4)`
我输的是这行，然后CyaRon给我返回了个
`Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    p = Polygon.simple_polygon(4)
  File "C:\Python33\lib\site-packages\cyaron\polygon.py", line 150, in simple_polygon
    raise Exception("source point is not a list")
Exception: source point is not a list`
接着我输入了个这个
`p = Polygon.simple_polygon([(0,0),(0,5),(5,6),(6,0)])`
然后就正常了。所以这是个Bug吗？

**Comment by qwedc001** [comment]
问题已解决，不用回复了，谢谢
