### ISSUE TITLE
对拍器的说明文档是不是有问题?

### ISSUE THREAD

**Issue by fearlessxjdx** [luogu-dev/cyaron#37]
我按照说明文档中提到的
```
while True:
    input_io = IO()
    input_io.input_writeln(randint(1,100))
    Compare.program("a.exe", "b.exe", input=input_io, std_program="std.exe") 
# 不断地生成测试数据（这里是1到100的随机数），然后放到a.exe，b.exe中，分别以std.exe为标准进行对拍比较
# CYaRon 现在使用多线程比较器，原 stop_on_incorrect 参数现已 deprecated 且无实际作用。
# 并在工作目录下输出a.exe.out, std.out, error_input.in三个文件方便您进一步调试。
```
进行了操作，但是并没有出现a.exe.out, std.out, error_input.in三个文件，只有一个异常
```
Traceback (most recent call last):
  File "F:\xjdx\test.py", line 9, in <module>
    Compare.program("a.exe", "b.exe", input=input_io, std_program="std.exe")
  File "D:\Program Files\Python36\lib\site-packages\cyaron\compare.py", line 143, in program
    [x for x in map(do, programs)]
  File "D:\Program Files\Python36\lib\site-packages\cyaron\compare.py", line 143, in <listcomp>
    [x for x in map(do, programs)]
  File "D:\Program Files\Python36\lib\site-packages\cyaron\compare.py", line 138, in do
    cls.__compare_two(program_name, content, std, grader)
  File "D:\Program Files\Python36\lib\site-packages\cyaron\compare.py", line 28, in __compare_two
    raise CompareMismatch(name, info)
cyaron.compare.CompareMismatch: ('a.exe', TextMismatch('123', '456', 'On line {} column {}, read {}, expected {}.', 1, 1, '123', '456'))
```

**Comment by WAAutoMaton** [comment]
像是cyraon有bug？
抛出了一个CompareMismatch之后就没有捕获了

**Comment by fearlessxjdx** [comment]
是啊,好奇怪
看了下Compare.py文件 好像也没有看到文档提到的写入文件操作.

**Comment by lin714093880** [comment]
Doc might be outdated

**Comment by fearlessxjdx** [comment]
@lin714093880 是否可以提供一个持续对拍,并将不同结果写入到其他文件的demo?

**Comment by TitanSnow** [comment]
Sorry, it seems to be my blame. I will look into it. 😮

**Comment by Himself65** [comment]
these bugs have fixed on the latest version.
