### ISSUE TITLE
output_gen是否不支持多笔输入的文件？

### ISSUE THREAD

**Issue by Visors** [luogu-dev/cyaron#72]
我通过
`while (cin >> s)`
输入一行空格分隔的不定长句子，使用output_gen获得输出时报错
`Traceback (most recent call last):
  File "C:/Users/Visors/Desktop/Round#1/cyaron/source/A.py", line 19, in <module>
    data_file.output_gen(r"F:\ACMLAB\SCPC\SCPC_Round#1\A.exe")
  File "C:\Users\Visors\Anaconda3\lib\site-packages\cyaron\io.py", line 171, in output_gen
    subprocess.check_call(shell_cmd, shell=True, stdin=self.input_file, stdout=self.output_file, universal_newlines=True)
  File "C:\Users\Visors\Anaconda3\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'F:\ACMLAB\SCPC\SCPC_Round#1\A.exe' returned non-zero exit status 1.`

**Comment by weilycoder** [comment]
你的程序好像以非零状态退出了，这导致了报错。

**Comment by Mr-Python-in-China** [comment]
你的程序的问题
